parse_config:
  raw_binding_map:
    "&cad": "CAD"
    "&alt_space": "APP"
    "&kp LG(LS(N3))": "SS3"
    "&kp LG(LS(N5))": "SS5"
    "&caps_word": "CAPW"
    "&bootloader": "BOOT"
    "&sys_reset": "RESET"
    "&display_power DISPLAY_POWER_INFO_CMD": "INFO"
    "&display_power DISPLAY_POWER_CYCLE_CMD": "DISP"
    "&dpwr DISPLAY_POWER_INFO_CMD": "INFO"
    "&dpwr DISPLAY_POWER_CYCLE_CMD": "DISP"
    "&mmv MOVE_UP": "M↑"
    "&mmv MOVE_DOWN": "M↓"
    "&mmv MOVE_LEFT": "M←"
    "&mmv MOVE_RIGHT": "M→"
    "&msc SCRL_UP": "S↑"
    "&msc SCRL_DOWN": "S↓"
    "&msc SCRL_LEFT": "S←"
    "&msc SCRL_RIGHT": "S→"
    "&mkp LCLK": "LCLK"
    "&mkp RCLK": "RCLK"
    "&mkp MCLK": "MCLK"
